
package com.macisdev.pizzasfxclient.webservicereference;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PizzaService", targetNamespace = "http://pizzawebservice.macisdev.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PizzaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendOrder", targetNamespace = "http://pizzawebservice.macisdev.com/", className = "com.macisdev.pizzasfxclient.webservicereference.SendOrder")
    @ResponseWrapper(localName = "sendOrderResponse", targetNamespace = "http://pizzawebservice.macisdev.com/", className = "com.macisdev.pizzasfxclient.webservicereference.SendOrderResponse")
    @Action(input = "http://pizzawebservice.macisdev.com/PizzaService/sendOrderRequest", output = "http://pizzawebservice.macisdev.com/PizzaService/sendOrderResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://pizzawebservice.macisdev.com/PizzaService/sendOrder/Fault/IOException")
    })
    public boolean sendOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrders", targetNamespace = "http://pizzawebservice.macisdev.com/", className = "com.macisdev.pizzasfxclient.webservicereference.GetOrders")
    @ResponseWrapper(localName = "getOrdersResponse", targetNamespace = "http://pizzawebservice.macisdev.com/", className = "com.macisdev.pizzasfxclient.webservicereference.GetOrdersResponse")
    @Action(input = "http://pizzawebservice.macisdev.com/PizzaService/getOrdersRequest", output = "http://pizzawebservice.macisdev.com/PizzaService/getOrdersResponse")
    public List<String> getOrders();

}
