
package com.macisdev.pizzasfxclient.webservicereference;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PizzaService", targetNamespace = "http://pizzawebservice.macisdev.com/", wsdlLocation = "http://localhost:8080/PizzasWebService/PizzaService?WSDL")
public class PizzaService_Service
    extends Service
{

    private final static URL PIZZASERVICE_WSDL_LOCATION;
    private final static WebServiceException PIZZASERVICE_EXCEPTION;
    private final static QName PIZZASERVICE_QNAME = new QName("http://pizzawebservice.macisdev.com/", "PizzaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PizzasWebService/PizzaService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PIZZASERVICE_WSDL_LOCATION = url;
        PIZZASERVICE_EXCEPTION = e;
    }

    public PizzaService_Service() {
        super(__getWsdlLocation(), PIZZASERVICE_QNAME);
    }

    public PizzaService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PIZZASERVICE_QNAME, features);
    }

    public PizzaService_Service(URL wsdlLocation) {
        super(wsdlLocation, PIZZASERVICE_QNAME);
    }

    public PizzaService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PIZZASERVICE_QNAME, features);
    }

    public PizzaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PizzaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PizzaService
     */
    @WebEndpoint(name = "PizzaServicePort")
    public PizzaService getPizzaServicePort() {
        return super.getPort(new QName("http://pizzawebservice.macisdev.com/", "PizzaServicePort"), PizzaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PizzaService
     */
    @WebEndpoint(name = "PizzaServicePort")
    public PizzaService getPizzaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pizzawebservice.macisdev.com/", "PizzaServicePort"), PizzaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PIZZASERVICE_EXCEPTION!= null) {
            throw PIZZASERVICE_EXCEPTION;
        }
        return PIZZASERVICE_WSDL_LOCATION;
    }

}
