
package com.macisdev.pizzasfxclient.webservicereference;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PizzaShopWebService", targetNamespace = "http://pizzashopwebservice.macisdev.com/", wsdlLocation = "http://localhost:8080/PizzaShopWebService/PizzaShopWebService?WSDL")
public class PizzaShopWebService
    extends Service
{

    private final static URL PIZZASHOPWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException PIZZASHOPWEBSERVICE_EXCEPTION;
    private final static QName PIZZASHOPWEBSERVICE_QNAME = new QName("http://pizzashopwebservice.macisdev.com/", "PizzaShopWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PizzaShopWebService/PizzaShopWebService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PIZZASHOPWEBSERVICE_WSDL_LOCATION = url;
        PIZZASHOPWEBSERVICE_EXCEPTION = e;
    }

    public PizzaShopWebService() {
        super(__getWsdlLocation(), PIZZASHOPWEBSERVICE_QNAME);
    }

    public PizzaShopWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PIZZASHOPWEBSERVICE_QNAME, features);
    }

    public PizzaShopWebService(URL wsdlLocation) {
        super(wsdlLocation, PIZZASHOPWEBSERVICE_QNAME);
    }

    public PizzaShopWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PIZZASHOPWEBSERVICE_QNAME, features);
    }

    public PizzaShopWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PizzaShopWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PizzaShopService
     */
    @WebEndpoint(name = "PizzaShopServicePort")
    public PizzaShopService getPizzaShopServicePort() {
        return super.getPort(new QName("http://pizzashopwebservice.macisdev.com/", "PizzaShopServicePort"), PizzaShopService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PizzaShopService
     */
    @WebEndpoint(name = "PizzaShopServicePort")
    public PizzaShopService getPizzaShopServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pizzashopwebservice.macisdev.com/", "PizzaShopServicePort"), PizzaShopService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PIZZASHOPWEBSERVICE_EXCEPTION!= null) {
            throw PIZZASHOPWEBSERVICE_EXCEPTION;
        }
        return PIZZASHOPWEBSERVICE_WSDL_LOCATION;
    }

}
